version: '3.7'

services:
  app:
    build: .
    ports:
      - "8088:8080"
    restart: always
    environment:
      STORAGE_TYPE: "postgres"
      DATABASE_URL: "postgres://user:password@db:5432/postgres?sslmode=disable"
    depends_on:
      - db
    networks:
      - mynetwork

  db:
    image: postgres:16
    volumes:
#      - ./build/data:/home/data
      - ./build/init.sql:/docker-entrypoint-initdb.d/10-init.sql
#      - ./build/copy.sql:/docker-entrypoint-initdb.d/20-copy.sql
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "54322:5432"
    networks:
      - mynetwork

networks:
  mynetwork:
