// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Comment struct {
	ID        string     `json:"id"`
	PostID    string     `json:"postId"`
	ParentID  *string    `json:"parentId,omitempty"`
	Content   string     `json:"content"`
	CreatedAt string     `json:"createdAt"`
	Replies   []*Comment `json:"replies"`
}

type Mutation struct {
}

type Post struct {
	ID              string     `json:"id"`
	Title           string     `json:"title"`
	Content         string     `json:"content"`
	Comments        []*Comment `json:"comments"`
	CommentsEnabled bool       `json:"commentsEnabled"`
}

type Query struct {
}

type Subscription struct {
}
